### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by doegox** [scateu/gr-remotecar#1]
Hi

You should remove the "build" rep from sources and update the instructions in readme, there is a missing cmake:

```
mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig
```

**Comment by scateu** [comment]
Thanks!  I will update the README.

**Comment by scateu** [comment]
Done.

**Comment by zemunkh** [comment]
Hi

Installed successfully on GNU radio. However, when compiling your examples in GNU Radio.
there is error about compiling remotecar_block in GNU Radio. This is not found "import remotecar" python library.

There is no remotecar Python Library in this project. Please help me to fix this error.
